### ISSUE TITLE
Keyboard backlight no longer responsive to hotkey

### ISSUE THREAD

**Issue by KinshipCourier** [pop-os/system76-dkms#13]
Distribution (run cat /etc/os-release):

NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Related Application and/or Package Version (run apt policy $PACKAGE NAME):
system76-dkms

system76-dkms:
Installed: 1.0.0153635127018.0493caafa
Candidate: 1.0.0153635127018.0493caafa
Version table:
*** 1.0.0153635127018.04~93caafa 1001
1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
100 /var/lib/dpkg/status

Issue/Bug Description:

I have an Oryx Pro 3. This package suddenly began controlling the keyboard backlight brightness and color scheme a while back. Now, it has completely ceased working, resulting in an always on, white backlight.

Steps to reproduce (if you know):

Expected behavior:
Keyboard Backlight hotkeys become useful during the beginning of the boot process and remains useful during system operation.

Other Notes:
I reinstalled Pop_OS! and Ubuntu LTS several times to see if it was a configuration issue. Nothing has yet helped.

**Comment by jackpot51** [comment]
@KinshipCourier can you try to reinstall the firmware by running `sudo system76-firmware` and clicking on `Reinstall Firmware`?

**Comment by KinshipCourier** [comment]
@jackpot51 Alrighty, I just reflashed the firmware successfully , but there's been no change with the keyboard backlight. I've upgraded the kernel to 4.17 branch and that didn't either. 4.18 kept throwing DKMS errors.

The firmware version is 
BIOS: 1.05.03RSA1
EC: 1.05.03MI2
EC2: N/A
ME 11.6.10.1196

**Comment by KinshipCourier** [comment]
I noticed that the red LED that illuminated the headphone jack socket is no longer on, too. It does flicker just before the boot process finishes and the desktop appears. I don't know if that helps any.

Also, just to be clear the keyboard backlight no longer shows up in the power menu either. The title seemed a bit ambiguous to that point.

**Comment by KinshipCourier** [comment]
I just ran lm-sensors in the terminal and noticed that the fan speeds are no longer displayed under the "system76" section at the end of the printout. I also went back to the standard kernel after I saw there was an update, applied several updates from system76-power and system76-driver(and -nvidia), went back to the 4.17 kernel and now the red LED in the headphone jack is working again.

I don't know if any of this is helping you, but I'll keep looking for changes.

**Comment by jackpot51** [comment]
I found that turning off the machine and then unplugging the power adapter reverts the backlight to firmware control.

**Comment by KinshipCourier** [comment]
Woah, that worked!

**Comment by jackpot51** [comment]
Glad to hear it

**Comment by ballisto** [comment]
> Woah, that worked! Awesome, thank you for your help! I would never have thought of that.

Same here, and same here. Still no idea why unplugging the adapter has anything to do with that. But it worked!
Thank you!

**Comment by ballisto** [comment]
> > Woah, that worked! Awesome, thank you for your help! I would never have thought of that.
> 
> Same here, and same here. Still no idea why unplugging the adapter has anything to do with that. But it worked!
> Thank you!

@jackpot51  This hint was somehow hard to find. I assume there are more Oryx Pro 3 owners out there with the same issue. Maybe it would be worth considering to put it on the System76 support page? At least that's where I started to look for a solution.
