### ISSUE TITLE
Add support for oryp3

### ISSUE THREAD

**Issue by raymond-w-ko** [pop-os/system76-dkms#18]
**Feature Request**
I have a Oryx Pro with a model designation of `oryp3`. If I try to load the stock module it complains that `Model does not utilize` this driver. My original intent for installing this driver is to gain access to fan controls as the automatic settings are very noisey. I tried changing https://github.com/pop-os/system76-dkms/blob/master/system76.c#L279 from `oryp3-jeremy` to `oryp3` and the fan controls worked, although GPU temperature `temp2_input` always reported a 0. I am using the proprietary NVIDIA drivers if that makes a difference.

The question: Is this model supported and the `oryp3` entry is just missing? Can support be added for this model?

**Comment by jackpot51** [comment]
This model is not supported. The dkms driver requires additional firmware support to function, which is only in the whitelisted models

**Comment by raymond-w-ko** [comment]
Do you think I should maintain my own mini-fork or is there a more official way of getting manual fan control?

**Comment by jackpot51** [comment]
You could maintain your own version, yes. We are implementing kernel drivers for fan control for all new models going forward. Not all of the features of the dkms driver will be supported for older models. If this is acceptable to you, you can continue utilizing your modified driver.

**Comment by raymond-w-ko** [comment]
Okay, thank you for the response.
