### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by electrickite** [pop-os/system76-dkms#2]
Will this project provide Github releases similar to system76-driver? If releases aren't planned, will commits be tagged with version numbers?

**Comment by jackpot51** [comment]
I would have the same response here as in: https://github.com/pop-os/system76-firmware/issues/3

**Comment by jackpot51** [comment]
I tagged the 0.0.3 release

**Comment by electrickite** [comment]
Thanks @jackpot51 ! Will a new release be tagged soon? It looks like there have been quite a few fixes over the last few months.
