### ISSUE TITLE
kbd_backlight missing after update

### ISSUE THREAD

**Issue by toxik-io** [pop-os/system76-dkms#25]
```
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
```

The program was a script of mine.
```
setcolor(){
	echo setting to $1
	setbrightness 255;
	sudo su -c "echo $1 > /sys/class/leds/system76\:\:kbd_backlight/color_left"
	sudo su -c "echo $1 > /sys/class/leds/system76\:\:kbd_backlight/color_center"
	sudo su -c "echo $1 > /sys/class/leds/system76\:\:kbd_backlight/color_right"
}
setbrightness(){
	sudo su -c "echo $1 > /sys/class/leds/system76\:\:kbd_backlight/brightness"
}
``` 
 
`/sys/class/leds/system76:kdb_backlight` doesn't exist anymore :C not sure... if the intel one (sys/class/backlight) can set colors.

Did... did Pop!_OS move it??

I don't have color control without that...

Side note, on the Darter Pro, only one of those `color_*`'s does anything... I was super excited to try it out on a multi-colored pad (still... the laptop rocks...)

**Comment by jackpot51** [comment]
The Darter Pro has a color keyboard with only one zone, whereas the Oryx Pro has three zones. So only one color will work. An update to restore the color files is available, please make sure you are up to date.

https://github.com/pop-os/system76-dkms/commit/5be9b0de58e6249fb399c774b58236e35a203aca#diff-7b8866814bfe5de7c6117c8f000b4232

**Comment by toxik-io** [comment]
1.0.4~1554501662~18.10~5be9b0d - that's the one I was running...

**Comment by jackpot51** [comment]
Have you rebooted since it was installed?

**Comment by toxik-io** [comment]
several times in the matermost group when regenerating / reinstalling stuff.
