### ISSUE TITLE
Gazelle (gaze14) - Keyboard light toggle no longer working

### ISSUE THREAD

**Issue by fagg** [pop-os/system76-dkms#32]
**Distribution (run `cat /etc/os-release`):**
 
[fagg@miranda][~][130] -> cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

![Screenshot from 2019-08-13 21-47-31](https://user-images.githubusercontent.com/1742468/62988914-012f2100-be14-11e9-9538-59226f3f4dd4.png)

system76 drivers are most definitely loaded:
![Screenshot from 2019-08-13 21-50-00](https://user-images.githubusercontent.com/1742468/62989007-608d3100-be14-11e9-807b-598ca052b482.png)

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

I believe it's system76-dkms

`fagg@miranda][~][0] -> apt policy system76-dkms
system76-dkms:
  Installed: 1.0.6~1565098100~18.04~f887e02~dev
  Candidate: 1.0.6~1565098100~18.04~f887e02~dev
  Version table:
 *** 1.0.6~1565098100~18.04~f887e02~dev 1001
       1001 http://ppa.launchpad.net/system76-dev/stable/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
[fagg@miranda][~][0] -> `

**Issue/Bug Description:**

System76 Gazelle (gaze14, 17" with 1660Ti) - keyboard light switch has suddenly stopped working. Can change colors and brightness, but the on/off button is no longer functional. Have confirmed that the key itself is fine, without pressing Fn the key enters "*" into a text field as expected.

**Steps to reproduce (if you know):**

Try and press the keyboard light trigger button (Fn + *).

**Expected behavior:**

Keyboard light should turn off.

**Other Notes:**

**Comment by brs17** [comment]
@fagg I am unable to recreate the issue on the same hardware with the same software setup. You could try to reinstall the system76-dkms to see if that fixes the issue. 

If the issue persists, I would recommend you contact System76 support and they can help you get to the bottom of your issue.
