### ISSUE TITLE
darp6 No known WMI event notification GUID found

### ISSUE THREAD

**Issue by tkolo** [pop-os/system76-dkms#39]
**Distribution (run `cat /etc/os-release`):**
 
 Arch Linux (also tested on Pop!_OS install cd)
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

system76-dkms-1.0.6

**Issue/Bug Description:**

This driver doesn't load on my darter pro with following output in dmesg:
```
[  379.999483] system76: Model System76 darp6 found
[  379.999486] system76: No known WMI event notification GUID found
```

**Steps to reproduce (if you know):**
`sudo modprobe system76`

**Expected behavior:**
Driver should load

**Other Notes:**
I'd seem to me that system76-acpi-dkms and system76-io-dkms have overtaken the role of this maybe?
I wanted to use this driver because it has more fine-grained control over keyboard's LED backlight.

**Comment by jackpot51** [comment]
system76-acpi-dkms is the correct driver to use
