### ISSUE TITLE
NVIDIA switch gone

### ISSUE THREAD

**Issue by Rami-Ha** [pop-os/system76-dkms#4]
Is this why I'm unable to switch from NVIDIA to Intel and back anymore? My Windows 10 VM on VMware Workstation is incapable of doing hardware acceleration now which tells me that it's unbale to detect the NVIDIA card.

**Comment by brs17** [comment]
By any chance did you remove `system76-power` or turn off the system76-power extension?

**Comment by brs17** [comment]
By any chance did you remove `system76-power` or disable the system76-power GNOME extension?
