### ISSUE TITLE
serw11 on Arch Linux 5.4.13-arch1-1 not supported

### ISSUE THREAD

**Issue by mliudev** [pop-os/system76-dkms#40]
**Distribution (run `cat /etc/os-release`):**
Arch Linux
Kernel Version: 5.4.13-arch1-1 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
package: system76-dkms (aur)
package url: https://aur.archlinux.org/packages/system76-dkms/
system: serw11

**Issue/Bug Description:**
Package does not provide backlight, airplane mode, or fan control (afaik), as described.

`dmesg | grep system76`
```
[   14.671625] system76: Model System76 serw11 found
[   14.671626] system76: Driver data not defined
[   15.185629] system76: Model System76 serw11 found
[   15.185630] system76: Driver data not defined
[   15.634402] system76: Model System76 serw11 found
[   15.634403] system76: Driver data not defined
[   15.634778] snd_hda_intel 0000:00:1f.3: Applying patch firmware 'system76-audio-patch'
```

`sudo modprobe -v system76`
```
insmod /lib/modules/5.4.13-arch1-1/updates/dkms/system76.ko.xz
modprobe: ERROR: could not insert 'system76': No such device
```

`ls /sys/class/leds/`
```
input5::capslock@  input5::numlock@  input5::scrolllock@  mmc0::@  phy0-led@
```
 Note that keyboard leds don't show up.

**Steps to reproduce (if you know):**
Arch Linux 5.4.13-arch1-1 running on serw11 and installing system76-dkms from the (AUR) does not provide the described support.

**Expected behavior:**
Installing the driver should provide support for keyboard backlights.

**Other Notes:**
Seems like serw11 isn't supported?

**Comment by jackpot51** [comment]
See https://github.com/pop-os/system76-dkms/pull/36

**Comment by mliudev** [comment]
> See #36

Thanks! This does fix my problem.
