### ISSUE TITLE
Keyboard color control

### ISSUE THREAD

**Issue by NathanaelA** [pop-os/system76-dkms#50]
**Issue/Bug Description:**
Is their any documentation on how to send color commands per key; obviously every single key has its own color led, so using the USB device (048d:8297) appears to be the color controller (IT8297 RGB LED Controller)?

**Comment by jackpot51** [comment]
Please see this file:

https://github.com/pop-os/system76-power/blob/master/src/hid_backlight.rs

**Comment by NathanaelA** [comment]
@jackpot51 - One more question -- this is awesome stuff.   I'm able to control each key and figured out that the IT8297 chip is actually used for the four Lighting sections.   So I can control it also totally independently also...

Somehow in all my playing the other day trying different open source RGB control projects I manage to somehow make the "lighting" led's become unsync'd so the lighting command was only changing a single led of the back right LED group.    Are their any docs on how to individually change each of the four regions and even how to change each of the leds in a region.    On startup of the computer you can also see the bios only activates a back right a single led to green, and all the other "lighting" led's are off.   

Are their any docs anywhere on either the 0x8297 or 0x8910 devices chipsets?

P.S. If it helps everything I do will be open sourced...
