### ISSUE TITLE
Kernel 5.10: No rule to make target 'scripts/module.lds'

### ISSUE THREAD

**Issue by 24fpsDaVinci** [pop-os/system76-dkms#51]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 20.10 x86_64 
 Kernel: 5.10.0-051000rc5-generic 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

make[3]: *** No rule to make target 'scripts/module.lds', needed by '/home/me/system76-dkms/system76.ko'.  Stop.

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by jacobgkau** [comment]
I am not able to recreate this issue. I can compile successfully by cloning the repo and running `make`.

Pop!_OS 20.10 is currently shipping with a 5.8 kernel. Since we haven't tested and are not currently supporting a 5.10 kernel, I would assume that is the issue.

**Comment by Moxinilian** [comment]
I also encounter this same issue on 5.10.1 with Pop!_OS 20.10 x86_64.
I believe this has been addressed and fixed on Ubuntu: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1906131

**Comment by crawfxrd** [comment]
Issue was fixed upstream.

Ref: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=975571
