### ISSUE TITLE
could not insert module system76.ko: Unknown symbol in module

### ISSUE THREAD

**Issue by ghost** [pop-os/system76-dkms#55]
**Distribution (run `cat /etc/os-release`):**
 NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
system76-dkms

**Issue/Bug Description:**
loading the kernel module with 
`$ sudo insmod system76.ko `
results in:
`insmod: ERROR: could not insert module system76.ko: Unknown symbol in module `

**Steps to reproduce (if you know):**
`$ unzip system65-dkms-master.zip`
`$ make`
`$ sudo modprobe -r system76`
`$ sudo insmod system76.ko`

**Expected behavior:**
The module should load successfully

**Other Notes:**
N/A

**Comment by szydell** [comment]
That is a DKMS module. The steps you're following are wrong.
Try dkms 'add', 'build' and 'install'.
