### ISSUE TITLE
Backlight does not work on bonw13

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/system76-dkms#60]
Backlit Keyboard Does Not Light After Pop!_OS 22.04 LTS Upgrade

**Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com/"
SUPPORT_URL="https://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 ```

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
system76-dkms:
  Installed: 1.0.14~1643391291~22.04~78ede46
  Candidate: 1.0.14~1643391291~22.04~78ede46
  Version table:
 *** 1.0.14~1643391291~22.04~78ede46 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.14~1643391291~22.04~78ede46~dev 1001
       1001 https://ppa.launchpadcontent.net/system76-dev/stable/ubuntu jammy/main amd64 Packages
```

**Issue/Bug Description:**

Key combo does not work to adjust backlit

Files are in the correct place:

```
ls /sys/class/leds/system76::kbd_backlight/
brightness  brightness_hw_changed  color_center  color_extra  color_left  color_right  device  max_brightness  power  subsystem  trigger  uevent
```

**Steps to reproduce (if you know):**

Install either Pop 20.04 or Pop 22.04 and the backlit is not adjustable in either a live disk, after the install or after updates.

**Expected behavior:**

The key combos work and you can echo into the files in /sys/class/leds

**Other Notes:**

**Comment by crawfxrd** [comment]
Does reverting https://github.com/pop-os/system76-dkms/pull/54 resolve the issue?

**Comment by crawfxrd** [comment]
And what is the firmware version?

1.05.04RSA5 has the note "Fixed keyboard backlight issues".

**Comment by leviport** [comment]
I got the bonw13 lab unit set up, and it's on `1.05.04RSA5-1`, and the keyboard backlight isn't working. I'll try reverting that commit to see if it makes a difference.

**Comment by leviport** [comment]
Fixed by https://github.com/pop-os/system76-dkms/pull/65
