### ISSUE TITLE
Not building in Linux 6.11.x

### ISSUE THREAD

**Issue by beholders-eye** [pop-os/system76-dkms#67]
**Distribution (run `cat /etc/os-release`):** Exherbo
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** gcc-13.3.0

**Issue/Bug Description:** Not building in Linux-6.11.x

**Steps to reproduce (if you know):**
make

**Expected behavior:**
To build the module properly.

**Other Notes:**

```
/usr/src/system76-dkms/system76.c:283:19: error: initialization of 'void (*)(struct platform_device *)' from incompatible pointer type 'int (*)(struct platform_device *)' [-Werror=incompatible-pointer-types]
  283 |         .remove = s76_remove,
      |                   ^~~~~~~~~~
/usr/src/system76-dkms/system76.c:283:19: note: (near initialization for 's76_platform_driver.<anonymous>.remove')
```

**Comment by crawfxrd** [comment]
Ref:

- torvalds/linux@5c5a7680e67 ("platform: Provide a remove callback that returns no value")
- torvalds/linux@0edb555a65d1 ("platform: Make platform_driver::remove() return void")

**Comment by nickgerace** [comment]
I think this works now, at least on NixOS.
